package eRSPG.model.form;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import static org.testng.Assert.*;

/**
 * Unit tests for BudgetForm model.
 */
public class BudgetFormTest {

    @BeforeMethod
    public void setUp() throws Exception {

    }

    @Test
    public void testStudentAssistants() throws Exception {

    }

    @Test
    public void testA1() throws Exception {

    }

    @Test
    public void testA2() throws Exception {

    }

    @Test
    public void testA3() throws Exception {

    }

    @Test
    public void testA4() throws Exception {

    }

    @Test
    public void testaBen() throws Exception {

    }

    @Test
    public void testB1() throws Exception {

    }

    @Test
    public void testB2() throws Exception {

    }

    @Test
    public void testB3() throws Exception {

    }

    @Test
    public void testB4() throws Exception {

    }

    @Test
    public void testbBen() throws Exception {

    }

    @Test
    public void testC1() throws Exception {

    }

    @Test
    public void testC2() throws Exception {

    }

    @Test
    public void testC3() throws Exception {

    }

    @Test
    public void testC4() throws Exception {

    }

    @Test
    public void testcBen() throws Exception {

    }

    @Test
    public void testSource1_a_1() throws Exception {

    }

    @Test
    public void testSource2_a_1() throws Exception {

    }

    @Test
    public void testSource3_a_1() throws Exception {

    }

    @Test
    public void testRequested_a_1() throws Exception {

    }

    @Test
    public void testSource1_b_1() throws Exception {

    }

    @Test
    public void testSource2_b_1() throws Exception {

    }

    @Test
    public void testSource3_b_1() throws Exception {

    }

    @Test
    public void testRequested_b_1() throws Exception {

    }

    @Test
    public void testSource1_c_1() throws Exception {

    }

    @Test
    public void testSource2_c_1() throws Exception {

    }

    @Test
    public void testSource3_c_1() throws Exception {

    }

    @Test
    public void testRequested_c_1() throws Exception {

    }

    @Test
    public void testSource1_a_ben() throws Exception {

    }

    @Test
    public void testSource2_a_ben() throws Exception {

    }

    @Test
    public void testSource3_a_ben() throws Exception {

    }

    @Test
    public void testRequested_a_ben() throws Exception {

    }

    @Test
    public void testSource1_b_ben() throws Exception {

    }

    @Test
    public void testSource2_b_ben() throws Exception {

    }

    @Test
    public void testSource3_b_ben() throws Exception {

    }

    @Test
    public void testRequested_b_ben() throws Exception {

    }

    @Test
    public void testSource1_c_ben() throws Exception {

    }

    @Test
    public void testSource2_c_ben() throws Exception {

    }

    @Test
    public void testSource3_c_ben() throws Exception {

    }

    @Test
    public void testRequested_c_ben() throws Exception {

    }

    @Test
    public void testSource1_a_2() throws Exception {

    }

    @Test
    public void testSource2_a_2() throws Exception {

    }

    @Test
    public void testSource3_a_2() throws Exception {

    }

    @Test
    public void testRequested_a_2() throws Exception {

    }

    @Test
    public void testSource1_b_2() throws Exception {

    }

    @Test
    public void testSource2_b_2() throws Exception {

    }

    @Test
    public void testSource3_b_2() throws Exception {

    }

    @Test
    public void testRequested_b_2() throws Exception {

    }

    @Test
    public void testSource1_c_2() throws Exception {

    }

    @Test
    public void testSource2_c_2() throws Exception {

    }

    @Test
    public void testSource3_c_2() throws Exception {

    }

    @Test
    public void testRequested_c_2() throws Exception {

    }

    @Test
    public void testSource1_a_3() throws Exception {

    }

    @Test
    public void testSource2_a_3() throws Exception {

    }

    @Test
    public void testSource3_a_3() throws Exception {

    }

    @Test
    public void testRequested_a_3() throws Exception {

    }

    @Test
    public void testSource1_b_3() throws Exception {

    }

    @Test
    public void testSource2_b_3() throws Exception {

    }

    @Test
    public void testSource3_b_3() throws Exception {

    }

    @Test
    public void testRequested_b_3() throws Exception {

    }

    @Test
    public void testSource1_c_3() throws Exception {

    }

    @Test
    public void testSource2_c_3() throws Exception {

    }

    @Test
    public void testSource3_c_3() throws Exception {

    }

    @Test
    public void testRequested_c_3() throws Exception {

    }

    @Test
    public void testSource1_a_4() throws Exception {

    }

    @Test
    public void testSource2_a_4() throws Exception {

    }

    @Test
    public void testSource3_a_4() throws Exception {

    }

    @Test
    public void testRequested_a_4() throws Exception {

    }

    @Test
    public void testSource1_b_4() throws Exception {

    }

    @Test
    public void testSource2_b_4() throws Exception {

    }

    @Test
    public void testSource3_b_4() throws Exception {

    }

    @Test
    public void testRequested_b_4() throws Exception {

    }

    @Test
    public void testSource1_c_4() throws Exception {

    }

    @Test
    public void testSource2_c_4() throws Exception {

    }

    @Test
    public void testSource3_c_4() throws Exception {

    }

    @Test
    public void testRequested_c_4() throws Exception {

    }

    @Test
    public void testSource1Total() throws Exception {

    }

    @Test
    public void testSource2Total() throws Exception {

    }

    @Test
    public void testSource3Total() throws Exception {

    }

    @Test
    public void testRequestedTotal() throws Exception {

    }

    @Test
    public void testGrandTotal() throws Exception {

    }
}